version: '3'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: nest
      MYSQL_USER: test
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: